#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist of the SalineOS project. https://github.com/SalineOS  salinelinux@gmail.com 
## Copyright 2013 Anthony Nordquist 

## Load translations

LanguageLess="$(echo "$LANG" | awk -F '.' '{print $1}')"

if [ -f /etc/thunar-actions-images/Translations/$LanguageLess ]; then
 . /etc/thunar-actions-images/Translations/$LanguageLess
else
 . /etc/custom-actions/Translations/en_US
fi

## Set arrays for yad options
Title=( "--title=Crop Image(s)" )
WindowIcon=( "--window-icon=image-x-generic" )
Icon=( "--image=image-x-generic" )

CropTo=$(yad --list --height=300 --column="$SELECTONE" --no-headers "${Title[@]}" "${WindowIcon[@]}" --text="Select the percentage to crop off edges." "1%" "2%" "3%" "4%" "5%" "6%" "7%" "8%" "9%" "10%" "11%" "12%" "13%" "14%" "15%" "16%" "17%" "18%" "19%" "20%" "21%" "22%" "23%" "24%" "25%" "26%" "27%" "28%" "29%" "30%" "31%" "32%" "33%" "34%" "35%" "36%" "37%" "38%" "39%" "40%" "41%" "42%" "43%" "44%" "45%" "46%" "47%" "48%" "49%" "50%" )

ret="$?"

CropTo=$(echo "$CropTo" | awk -F '|' '{print $1}')

if [ "$ret" = "1" ]; then
 exit
elif [ "$ret" = "252" ]; then
 exit
elif [ "$CropTo" = "" ]; then
 yad --window-icon="error" --image="error" "${Title[@]}" --width="350" --wrap --text="$NOPERCENT\n" --button=$"gtk-quit:1"
 exit 0
fi

## Do some crop to math
CropTo=$(echo "$CropTo" | sed -e 's|%||g')
CropTo=$((100 - $CropTo))

## Allow saving files to a different folder

CurrentDirectory="$(pwd)"

Destination=$(yad "${Title[@]}" "${WindowIcon[@]}" --file-selection --text-align="center" --height="500" --width="600" --directory --text="$CROPFILE\n" --title="Crop Image(s)" --button=$"gtk-quit:3" --button=$"gtk-ok:2")

ret="$?"


if [ "$ret" = "252" ]; then
 exit
elif [ "$ret" = "3" ]; then
 exit
elif [ "$Destination" = "" ]; then
 yad --window-icon="error" --image="error" --width="350" --wrap --text="$NODESTINATION\n" --button=$"gtk-quit:1"
fi

## Check to see if we are overwriting files and prompt the user


if [ "$CurrentDirectory" = "$Destination" ]; then
 yad "${Title[@]}" --window-icon="emblem-important" --image="emblem-important" --wrap --width="350" --text="$CROPAPPEND" --button=$"gtk-cancel:7" --button=$"$OVERWRITEFILES:3" --button=$"$APPENDBUTTON:5"
 ret="$?"

if [ "$ret" = "252" ]; then
 exit
elif [ "$ret" = "5" ]; then
 Overwrite="False"
elif [ "$ret" = "7" ]; then
 exit
fi

fi

progressbar () {
tail -f /usr/bin/crop-image-ca |  yad "${Title[@]}" "${WindowIcon[@]}" "${Icon[@]}" --width="350" --wrap --progress --no-buttons --pulsate --auto-close --text="$@"
}

progressbar "$CROPPROGRESS\n" &

for i in "$@"; do
 Extension="$(echo "$i" | awk -F "." '{print $NF}')"
 Cropped="$(echo "$i" | sed -e "s|.$Extension||g")"
 if [ "$Overwrite" = "False" ]; then
  convert "./$i" -gravity Center -crop $CropTo%/! "$Destination/$Cropped"-Cropped."$Extension"
 else
  convert "./$i" -gravity Center -crop $CropTo%/! "$Destination/$i"
 fi
done

sleep 5

TailPID=$(pgrep -f "tail -f /usr/bin/crop-image-ca")

kill $TailPID

notify-send -u normal -i image-x-generic -t 25000 "
$CROPCOMPLETE"

exit
