#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist of the SalineOS project. https://github.com/SalineOS  salinelinux@gmail.com 
## Copyright 2011,2012 Anthony Nordquist 

## Load translations

LanguageLess="$(echo "$LANG" | awk -F '.' '{print $1}')"

if [ -f /etc/thunar-image-scripts/Translations/$LanguageLess ]; then
 . /etc/thunar-image-scripts/Translations/$LanguageLess
else
 . /etc/thunar-image-scripts/Translations/en_US
fi

## Set arrays for yad options
Title=( "--title=Resize Image(s)" )
WindowIcon=( "--window-icon=image-x-generic" )
Icon=( "--image=image-x-generic" )

ResizeTo=$(yad "${Title[@]}" "${WindowIcon[@]}" --list --height=300 --column="$SELECTONE" --no-headers --text="Select the percentage to resize to." 10% 15% 20% 25% 30% 35% 40% 45% 50% 55% 60% 65% 70% 75% 80% 85% 90% 95% 100% 105% 110% 115% 120% 125% 130% 135% 140% 145% 150% 155% 160% 165% 170% 175% 180% 185% 190% 195% 200%)

ret="$?"

ResizeTo=$(echo "$ResizeTo" | awk -F '|' '{print $1}')

if [ "$ret" = "1" ]; then
 exit
elif [ "$ret" = "252" ]; then
 exit
elif [ "$ResizeTo" = "" ]; then
 yad "${Title[@]}" --window-icon="error" --image="error" --width="350" --wrap --text="$NOPERCENT\n" --button=$"gtk-quit:1"
 exit 0
fi

## Allow saving files to a different folder

CurrentDirectory="$(pwd)"

Destination=$(yad "${Title[@]}" "${WindowIcon[@]}" --file-selection --height="450" --width="500" --text-align="center" --directory --text="$RESIZEFILE\n" --button=$"gtk-quit:3" --button=$"gtk-ok:2")

ret="$?"

if [ "$ret" = "252" ]; then
 exit
elif [ "$ret" = "3" ]; then
 exit
elif [ "$Destination" = "" ]; then
 yad "${Title[@]}" --window-icon="error" --image="error" --width="350" --wrap --text="$NODESTINATION\n" --button=$"gtk-quit:1"
fi

## Check to see if we are overwriting files and prompt the user


if [ "$CurrentDirectory" = "$Destination" ]; then
 yad "${Title[@]}" --window-icon="important" --image="important" --wrap --width="350" --text="$APPENDOVERWRITE" --button=$"gtk-cancel:7" --button=$"$OVERWRITEFILES:3" --button=$"$APPENDBUTTON:5"
 ret="$?"

if [ "$ret" = "252" ]; then
 exit
elif [ "$ret" = "5" ]; then
 Overwrite="False"
elif [ "$ret" = "7" ]; then
 exit
fi

fi

progressbar () {
tail -f /usr/bin/resize-image-ca |  yad "${Title[@]}" "${WindowIcon[@]}" "${Icon[@]}" --width="350" --wrap --progress --no-buttons --pulsate --auto-close --text="$@"
}

progressbar "$PRESIZE $ResizeTo $NOW\n" &

for i in "$@"; do
 Extension="$(echo "$i" | awk -F "." '{print $NF}')"
 Resized="$(echo "$i" | sed -e "s|.$Extension||g")"
 if [ "$Overwrite" = "False" ]; then
  convert "./$i" -resize $ResizeTo "$Destination/$Resized"-RESIZED."$Extension"
 else
  convert "./$i" -resize $ResizeTo "$Destination/$i"
 fi
done

sleep 5

TailPID=$(pgrep -f "tail -f /usr/bin/resize-image-ca")

kill $TailPID

notify-send -u normal -i image-x-generic -t 25000 "
$RESIZECOMPLETE"

exit
